name: retail_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.15+15

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  awesome_icons: ^1.1.0
  autocomplete_textfield: ^2.0.1
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.2
  #camera: ^0.10.0
  dio: ^5.4.3+1
  dropdown_button2: ^2.3.8
  email_validator: ^2.1.17
  flutter_toastr: ^1.0.3
  animated_custom_dropdown: ^3.0.0
  fluttertoast: ^8.2.5
  flutter_dropdown_search: ^0.0.4
  flutter_typeahead: ^5.2.0
  flutter_switch: ^0.3.2
  flutter_speed_dial: ^7.0.0
  grouped_list: ^5.1.2
  getwidget: ^4.0.0
  eva_icons_flutter: ^3.1.0
  font_awesome_flutter: ^10.8.0
  http: ^1.2.1
  hive: ^2.2.3
  intl: ^0.19.0
  change_app_package_name: ^1.4.0
  image_picker: ^1.1.0
  flutter_image_compress: ^2.0.3
  qr_code_scanner: ^1.0.1
  image_cropper: ^5.0.0
  flutter_barcode_scanner: ^2.0.0
  device_info_plus: ^11.1.1
  material_design_icons_flutter: ^7.0.7296
  local_auth: ^2.2.0
  nepali_date_picker: ^6.0.0
  nepali_utils: ^3.0.4
  open_filex: ^4.4.0
  page_transition: ^2.1.0
  path: ^1.9.0
  path_provider: ^2.1.3
  icons_plus: ^5.0.0
  pdf: ^3.10.8
  photo_view: ^0.14.0
  provider: ^6.1.2
  #printing: ^5.12.0
  package_info_plus: ^4.2.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  sunmi_printer_plus: ^2.1.1
  dotted_line: ^3.2.3
  permission_handler: ^11.3.1
  # google_maps_flutter: ^2.2.5
  geolocator: ^13.0.2
  #qr_code_scanner: ^0.4.0
  qr_flutter: ^4.1.0
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/mo_re.ttf

    - family: Montserrat Medium
      fonts:
        - asset: assets/fonts/mo_me.ttf

